name: Hansi
favicon: null
layout_spectrum: 0.24277
typography_spectrum: 0.9889327068813145
title: Hansi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c252d'
    - '#787f5a'
    - '#939c71'
    - '#3e4f29'
    - '#cabdaf'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
