name: Hansi
favicon: null
layout_spectrum: 0.24277
typography_spectrum: 0.49083
title: Hansi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1d9d6'
    - '#998785'
    - '#020202'
    - '#6e6663'
    - '#3c3431'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
